# Generated by Django 2.2.7 on 2020-02-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200210_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='userprofile.png', upload_to='upload'),
        ),
    ]
