# Generated by Django 2.2.7 on 2020-02-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
