# Generated by Django 2.2.7 on 2020-02-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_companyprofile_com_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_address',
            field=models.TextField(null=True),
        ),
    ]
