# Generated by Django 2.2.7 on 2020-02-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_companyprofile_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='benifit',
            field=models.TextField(null=True),
        ),
    ]
