# Generated by Django 2.2.7 on 2020-02-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_companyprofile_benifit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='com_img',
        ),
    ]
