# Generated by Django 3.0.5 on 2020-04-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_profile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to='File/'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='contact',
            field=models.TextField(blank=True, null=True),
        ),
    ]
