# Generated by Django 3.0.5 on 2020-04-29 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20200430_0534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='File',
            new_name='file',
        ),
    ]
