# Generated by Django 3.0.5 on 2020-04-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20200430_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='contact',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='prove',
            field=models.FileField(blank=True, null=True, upload_to='prove/'),
        ),
    ]
