# Generated by Django 2.2.7 on 2020-02-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='type_job',
            field=models.CharField(choices=[('Part time', 'Part time'), ('Full time', 'Full time')], max_length=200, null=True),
        ),
    ]
