# Generated by Django 2.2.7 on 2020-02-13 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0002_auto_20200214_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='author',
        ),
    ]
