# Generated by Django 2.2.7 on 2020-02-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0003_remove_jobpost_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPost',
        ),
    ]
