# Generated by Django 2.2.7 on 2020-02-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobboard', '0004_delete_jobpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True)),
                ('logo_img', models.ImageField(blank='True', upload_to='logo_img')),
                ('type_job', models.CharField(choices=[('Part time', 'Part time'), ('Full time', 'Full time')], max_length=200, null=True)),
            ],
        ),
    ]
