# Generated by Django 2.2.7 on 2020-02-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0005_postjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='logo_img',
            field=models.ImageField(default='userprofile.png', upload_to='logo_img'),
        ),
    ]
