# Generated by Django 2.2.7 on 2020-02-18 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0014_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='salary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobboard.Salary'),
        ),
    ]
