# Generated by Django 2.2.7 on 2020-02-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0015_postjob_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='company_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
