# Generated by Django 2.2.7 on 2020-02-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0017_postjob_benafit'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='company_detail',
            field=models.TextField(null=True),
        ),
    ]
