# Generated by Django 2.2.7 on 2020-02-19 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0020_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobboard.Gender'),
        ),
    ]
