# Generated by Django 2.2.7 on 2020-02-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0021_postjob_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='vacancy',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
