# Generated by Django 2.2.7 on 2020-02-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0022_postjob_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postjob',
            name='benafit',
        ),
    ]
