# Generated by Django 2.2.7 on 2020-02-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0024_postjob_benifit'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
