# Generated by Django 2.2.7 on 2020-02-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0025_postjob_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postjob',
            options={'ordering': ['-timestamp', '-date_posted']},
        ),
    ]
