# Generated by Django 2.2.7 on 2020-04-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0029_application_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postjob',
            name='logo_img',
        ),
    ]
