# Generated by Django 2.2.7 on 2020-04-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0032_auto_20200425_2224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
