# Generated by Django 2.2.7 on 2020-04-25 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0033_delete_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postjob',
            name='user',
        ),
    ]
