# Generated by Django 2.2.7 on 2020-04-26 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobboard', '0037_postjob_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('applicant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='recruits', to=settings.AUTH_USER_MODEL)),
                ('jobpost', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='jobboard.PostJob')),
            ],
        ),
    ]
