# Generated by Django 2.2.7 on 2020-04-27 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0044_application_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='jobpost',
        ),
    ]
