# Generated by Django 2.2.7 on 2020-04-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0047_remove_application_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='Resume_file/'),
        ),
    ]
