# Generated by Django 2.2.7 on 2020-04-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0048_application_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postjob',
            name='type_job',
        ),
    ]
