# Generated by Django 2.2.7 on 2020-04-27 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0050_type_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='type_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobboard.Type_Job'),
        ),
    ]
