# Generated by Django 2.2.7 on 2020-04-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0051_postjob_type_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
    ]
