# Generated by Django 2.2.7 on 2020-04-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0052_remove_application_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(null=True, upload_to='Resume'),
        ),
    ]
