# Generated by Django 2.2.7 on 2020-04-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0055_application_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='image',
            field=models.ImageField(default='userprofile.png', null=True, upload_to='resume_pic'),
        ),
    ]
