# Generated by Django 2.2.7 on 2020-04-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0056_application_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='image',
        ),
    ]
