# Generated by Django 2.2.7 on 2020-04-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0057_remove_application_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resume_pic'),
        ),
    ]
