# Generated by Django 2.2.7 on 2020-04-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0058_application_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='file',
            field=models.FileField(null=True, upload_to='resume_pic'),
        ),
    ]
