# Generated by Django 2.2.7 on 2020-04-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0059_auto_20200428_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='file',
        ),
    ]
