# Generated by Django 3.0.5 on 2020-04-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0062_auto_20200428_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='pdf',
            field=models.ImageField(blank=True, null=True, upload_to='Resume_pic/'),
        ),
    ]
