# Generated by Django 3.0.5 on 2020-04-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0063_application_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='pdf',
            field=models.ImageField(null=True, upload_to='Resume_pic/'),
        ),
    ]
