# Generated by Django 3.0.5 on 2020-04-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0064_auto_20200429_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='pdf',
        ),
        migrations.AddField(
            model_name='application',
            name='img',
            field=models.ImageField(default='userprofile.png', null=True, upload_to='resume_img'),
        ),
    ]
