# Generated by Django 3.0.5 on 2020-04-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0065_auto_20200429_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='img',
        ),
    ]
