# Generated by Django 3.0.5 on 2020-04-29 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0066_remove_application_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
    ]
