# Generated by Django 3.0.5 on 2020-04-29 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0067_remove_application_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['date_applied']},
        ),
        migrations.RemoveField(
            model_name='application',
            name='updated',
        ),
    ]
