# Generated by Django 3.0.5 on 2020-04-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0068_auto_20200429_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contact_app',
            field=models.TextField(blank=True, null=True),
        ),
    ]
