# Generated by Django 3.0.5 on 2020-04-30 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0069_application_contact_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postjob',
            name='benifit',
        ),
    ]
