# Generated by Django 3.0.5 on 2020-04-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0070_remove_postjob_benifit'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='contact_com',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='postjob',
            name='requirement',
            field=models.TextField(null=True),
        ),
    ]
